services:
  backend:
    image: ghcr.io/djalaljkeee/djvpn-lk-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default
      - shm-net

  frontend:
    image: ghcr.io/djalaljkeee/djvpn-lk-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: shm-cabinet
  shm-net:
    external: true
    name: ${SHM_NETWORK}
